[project]
name = "nano-vllm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "ruff>=0.12.7",
    "setuptools>=80.9.0",
    "torch>=2.7.1",
    "torchtyping>=0.1.5",
    "transformers>=4.54.1",
    "xxhash>=3.5.0",
]
