[project]
name = "nano-vllm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "flash-attn>=2.8.2",
    "ruff>=0.12.7",
    "torch>=2.7.1",
    "transformers>=4.54.1",
    "xxhash>=3.5.0",
]
